name: ci linting, testing, building
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build production
        run: npm run build:prod
        if: always()
      - name: Linting typescript
        run: npm run lint:ts
        if: always()
      - name: Linting css
        run: npm run lint:css
        if: always()
      - name: Run tests
        run: npm run test:unit
        if: always()
      - name: Build storybook
        run: npm run storybook:build
        if: always()
      - name: Run screenshot tests
        run: npm run chromatic
        if: always()
